apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cloudflare-tunnel
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: "https://github.com/The-Keep-Studios/thekeep-platform.git"
    targetRevision: "main"
    path: kubernetes/platform/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-authentik
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: "https://github.com/The-Keep-Studios/thekeep-platform.git"
    targetRevision: "main"
    path: kubernetes/platform/authentik
  destination:
    server: https://kubernetes.default.svc
    namespace: identity
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-leantime
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: "https://github.com/The-Keep-Studios/thekeep-platform.git"
    targetRevision: "main"
    path: kubernetes/apps/leantime
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-wisemapping
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: "https://github.com/The-Keep-Studios/thekeep-platform.git"
    targetRevision: "main"
    path: kubernetes/apps/wisemapping
  destination:
    server: https://kubernetes.default.svc
    namespace: wisemapping
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring-prometheus
  namespace: argocd
spec:
  project: platform
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.14.0
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
      - $values/kubernetes/platform/monitoring/kube-prometheus-stack.values.yaml
  - repoURL: "https://github.com/The-Keep-Studios/thekeep-platform.git"
    targetRevision: "main"
    ref: values
  - repoURL: "https://github.com/The-Keep-Studios/thekeep-platform.git"
    targetRevision: "main"
    path: kubernetes/platform/monitoring/access
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring-loki
  namespace: argocd
spec:
  project: platform
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.3
    helm:
      releaseName: loki
      valueFiles:
      - $values/kubernetes/platform/monitoring/loki-stack.values.yaml
  - repoURL: "https://github.com/The-Keep-Studios/thekeep-platform.git"
    targetRevision: "main"
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
